### ISSUE TITLE
判断不了

### ISSUE THREAD

**Issue by echoAndroid** [realdennis/xvideo-js#3]
(node:27918) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: missing ) after argument list
<img width="527" alt="2018-05-21 4 16 10" src="https://user-images.githubusercontent.com/16718550/40297492-a535e068-5d12-11e8-8550-a559a56404f4.png">

我的node版本
node -v
  v6.10.0
npm -v
  3.10.10

**Comment by realdennis** [comment]
建議升級Node/npm的版本，我在最新版本測試是正常的。
截圖中看不出程序的臭蟲所在（沒有辦法判斷是程序本身或是相依套件）

It is recommended to upgrade the node/NPM version and it is ok for me to use it in the latest version. **(Node v10/ npm v6)**
The bug where the program is not visible in this screenshot (there is no way to determine where the bug in my program or the 3rd dependency .)

**Comment by echoAndroid** [comment]
Ok,Thank you.

**Comment by realdennis** [comment]
嗨，我使用了Babel將較新版本的語法轉譯，實測在Node v6 / npm 3.10.0可以順利執行，祝您使用愉快。

Hey, I use babel to transpile my source code for lower node version (Test in node v6/ npm v3).
Have Fun.
